module.exports = {
  apps: [
    {
      name: process.env.PM2_APP_NAME || 'yali-canvas-api',
      cwd: process.env.APP_CWD || process.cwd(),
      script: 'apps/api/dist/src/server.js',
      interpreter: 'node',
      exec_mode: 'cluster',
      instances: Number(process.env.PM2_API_INSTANCES || 2),
      env: {
        NODE_ENV: process.env.NODE_ENV || 'production',
        PORT: process.env.PORT || 4010,
        HOST: process.env.HOST || '0.0.0.0',
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_URL: process.env.REDIS_URL,
        ADMIN_DATA_DIR: process.env.ADMIN_DATA_DIR || './data',
        PROVIDER_DATA_DIR: process.env.PROVIDER_DATA_DIR || './data',
        PUBLIC_API_BASE_URL: process.env.PUBLIC_API_BASE_URL,
        ADMIN_USERNAME: process.env.ADMIN_USERNAME,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        DEFAULT_TEST_REFERENCE_IMAGE_URL: process.env.DEFAULT_TEST_REFERENCE_IMAGE_URL,
        GENERATED_IMAGE_ACCEL_REDIRECT_PREFIX: process.env.GENERATED_IMAGE_ACCEL_REDIRECT_PREFIX || '/_generated-images',
      },
    },
    {
      name: process.env.PM2_WORKER_APP_NAME || 'yali-canvas-worker',
      cwd: process.env.APP_CWD || process.cwd(),
      script: 'apps/api/dist/src/worker.js',
      interpreter: 'node',
      env: {
        NODE_ENV: process.env.NODE_ENV || 'production',
        PORT: process.env.PORT || 4010,
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_URL: process.env.REDIS_URL,
        ADMIN_DATA_DIR: process.env.ADMIN_DATA_DIR || './data',
        PROVIDER_DATA_DIR: process.env.PROVIDER_DATA_DIR || './data',
        PUBLIC_API_BASE_URL: process.env.PUBLIC_API_BASE_URL,
        ADMIN_USERNAME: process.env.ADMIN_USERNAME,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        DEFAULT_TEST_REFERENCE_IMAGE_URL: process.env.DEFAULT_TEST_REFERENCE_IMAGE_URL,
        GENERATED_IMAGE_ACCEL_REDIRECT_PREFIX: process.env.GENERATED_IMAGE_ACCEL_REDIRECT_PREFIX || '/_generated-images',
        CANVAS_WORKER_ONLY: '1',
      },
    },
  ],
};
